// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezovtbdrackpcitzdloo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6b3Z0YmRyYWNrcGNpdHpkbG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5ODI4ODcsImV4cCI6MjA1NDU1ODg4N30.dSMSjDmWWjD4Dw57qbkcqFLlJYzsxuvJY5f2DcN2XhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);